plugins:
  sitetor_bds_enabled:
    default: true
    client: true
  sitetor_bds_categories:
    default: "3412|3722|3344|3698"
    type: list
    list_type: compact
    client: true
  sitetor_bds_usd_rate:
    default: 26000
    client: false
  sitetor_bds_page_size:
    default: 30
    client: true
